apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fibonacci-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: fibonacci
      app.kubernetes.io/name: fibonacci-chart
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s